config/routes.rb
Health::Application.routes.draw do
  match "admin" => "admin#index"
  namespace :admin do
    resources :doctors
    resources :specialities
    resources :worktimes
    resources :consultations
    resources :services
    resources :orders
    resources :posts
    resources :articles
  end

  match "about" => "index#about"
  root :to => "index#index"
  match "service" => "index#service"

  match "doctors" => "index#doctors"

  match "faq" => "index#faq"

  match "info" => "index#info"

  match "contact" => "index#contact"

  match "order" => "index#order"

  match "text" => "index#text"

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  #root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :description, :doctor_id
  belongs_to :doctor
  belongs_to :speciality

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

  def new
    @article = Article.new
  end

  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @post.update_attributes params[:article]
    redirect_to admin_articles_path(@article)
  end

  def create
    Article.create params[:article]
    redirect_to admin_articles_path
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to admin_articles_path
  end

end

app/views/admin/articles/_form.html.haml
= form_for [:admin, @article], :html => {:class => "form-horizontal"} do |f|

  .control-group
    %label.control-label Название статьи
    .controls
      = f.text_field :name

  .control-group
    %label.control-label Описание
    .controls
      =f.text_area :description, :style => "width:100%"

  .control-group
    %label.control-label Описание
    .controls
      = f.select :doctor_id, options_for_select(Doctor.all.map{|s| [s.fio, s.id]}, @article.doctor_id)

  .form-actions
    %input.btn.btn-success{:name => "save", :type => "submit", :value => "Сохранить"}
    = link_to "назад",admin_articles_path, :class => "btn"

app/views/admin/articles/index.html.haml
%table.table
  %tr
    %th #
    %th Название статьи
    %th Описание
    %th Удалить
  - @article.each do |d|
    %tr
      %td
        %a{href: "/admin/articles/#{d.id}"}=d.id
      %td= d.name
      %td= d.description
      %td
        =link_to "Удалить", admin_article_path(d), :method => :delete, :class => "btn btn-danger", :confirm => "Вы уверены?"



%a.btn{href: "/admin/articles/new"} Добавить

app/views/admin/articles/new.html.haml
= render "form"

app/views/admin/articles/show.html.haml
= render "form"